# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x19\x61i.djl.serving.grpc.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xde\x01\n\x10InferenceRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x1a\n\rmodel_version\x18\x02 \x01(\tH\x00\x88\x01\x01\x12I\n\x07headers\x18\x04 \x03(\x0b\x32\x38.ai.djl.serving.grpc.proto.InferenceRequest.HeadersEntry\x12\r\n\x05input\x18\x05 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x42\x10\n\x0e_model_version\"\xad\x01\n\x11InferenceResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12J\n\x07headers\x18\x02 \x03(\x0b\x32\x39.ai.djl.serving.grpc.proto.InferenceResponse.HeadersEntry\x12\x0e\n\x06output\x18\x03 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\xa0\x01\n\x0cPingResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12N\n\x0cmodel_status\x18\x02 \x03(\x0b\x32\x38.ai.djl.serving.grpc.proto.PingResponse.ModelStatusEntry\x1a\x32\n\x10ModelStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"`\n\x0c\x45mbedRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x1a\n\rmodel_version\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06inputs\x18\x03 \x03(\tB\x10\n\x0e_model_version\"*\n\tEmbedding\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"h\n\rEmbedResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x38\n\nembeddings\x18\x03 \x03(\x0b\x32$.ai.djl.serving.grpc.proto.Embedding2\x9e\x02\n\tInference\x12I\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\'.ai.djl.serving.grpc.proto.PingResponse\"\x00\x12h\n\x07Predict\x12+.ai.djl.serving.grpc.proto.InferenceRequest\x1a,.ai.djl.serving.grpc.proto.InferenceResponse\"\x00\x30\x01\x12\\\n\x05\x45mbed\x12\'.ai.djl.serving.grpc.proto.EmbedRequest\x1a(.ai.djl.serving.grpc.proto.EmbedResponse\"\x00\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_INFERENCEREQUEST_HEADERSENTRY']._options = None
  _globals['_INFERENCEREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_INFERENCERESPONSE_HEADERSENTRY']._options = None
  _globals['_INFERENCERESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_PINGRESPONSE_MODELSTATUSENTRY']._options = None
  _globals['_PINGRESPONSE_MODELSTATUSENTRY']._serialized_options = b'8\001'
  _globals['_INFERENCEREQUEST']._serialized_start=76
  _globals['_INFERENCEREQUEST']._serialized_end=298
  _globals['_INFERENCEREQUEST_HEADERSENTRY']._serialized_start=234
  _globals['_INFERENCEREQUEST_HEADERSENTRY']._serialized_end=280
  _globals['_INFERENCERESPONSE']._serialized_start=301
  _globals['_INFERENCERESPONSE']._serialized_end=474
  _globals['_INFERENCERESPONSE_HEADERSENTRY']._serialized_start=234
  _globals['_INFERENCERESPONSE_HEADERSENTRY']._serialized_end=280
  _globals['_PINGRESPONSE']._serialized_start=477
  _globals['_PINGRESPONSE']._serialized_end=637
  _globals['_PINGRESPONSE_MODELSTATUSENTRY']._serialized_start=587
  _globals['_PINGRESPONSE_MODELSTATUSENTRY']._serialized_end=637
  _globals['_EMBEDREQUEST']._serialized_start=639
  _globals['_EMBEDREQUEST']._serialized_end=735
  _globals['_EMBEDDING']._serialized_start=737
  _globals['_EMBEDDING']._serialized_end=779
  _globals['_EMBEDRESPONSE']._serialized_start=781
  _globals['_EMBEDRESPONSE']._serialized_end=885
  _globals['_INFERENCE']._serialized_start=888
  _globals['_INFERENCE']._serialized_end=1174
# @@protoc_insertion_point(module_scope)
